//
//  MeetingsStore.swift
//  Riverhead NY Budget App
//
//  Town Board Votes — the Board's voting record, straight from the Town's own
//  published minutes, plus the forward-looking "Coming up" schedule.
//
//  The web app's canonical meetings JSON is preferred at runtime so the native
//  app does not drift between App Store releases. The bundled MeetingsData/*.json
//  snapshot remains the offline fallback and is still generated by the shared ETL.
//
//  Swift 6 / iOS 17+
//

import Foundation

// MARK: - Index (list of every meeting on record)

struct MeetingsIndex: Decodable {
    let totals: Totals
    let meetings: [MeetingSummary]

    struct Totals: Decodable {
        let meetings: Int
        let votes: Int
        let contested: Int
        let failed: Int
        let tabled: Int
    }
}

struct MeetingSummary: Decodable, Identifiable {
    let slug: String
    let date: String
    let type: String
    let total: Int
    let unanimous: Int
    let contested: Int
    let failed: Int
    let tabled: Int
    let preliminary: Bool?
    let docketCount: Int?

    var id: String { slug }
    var isPreliminary: Bool { preliminary ?? false }
}

// MARK: - A single meeting

struct MeetingDetail: Decodable {
    let date: String
    let type: String
    let calledToOrder: String?
    let roster: [RosterMember]
    let resolutions: [Resolution]
    let preliminary: Bool?
    let docket: [DocketItem]?

    var isPreliminary: Bool { preliminary ?? false }
}

struct RosterMember: Decodable, Identifiable {
    let last: String
    let name: String
    let title: String
    let party: String?

    var id: String { last }
}

struct Resolution: Decodable, Identifiable {
    let seq: Int
    let number: String?
    let title: String
    let result: String?
    let adopted: Bool?
    let tag: String?
    let ayesCount: Int?
    let naysCount: Int?
    let mover: String?
    let seconder: String?
    let votes: [String: String]?

    var id: Int { seq }
}

struct DocketItem: Decodable, Identifiable {
    let seq: Int
    let number: String
    let title: String

    var id: Int { seq }
}

// MARK: - Coming up (forward-looking companion to the voting record)

struct UpcomingMeeting: Decodable, Identifiable {
    let slug: String
    let date: String
    let startDateTime: String
    let type: String
    let agendaPublished: Bool
    let docket: [DocketItem]
    let hearings: [String]

    var id: String { startDateTime }
}

private struct UpcomingFile: Decodable { let meetings: [UpcomingMeeting] }

// MARK: - Loader

enum RBMeetingsData {
    /// Bundled snapshot used for immediate rendering and offline fallback.
    static let index: MeetingsIndex? = loadBundled("index")

    static func meeting(_ slug: String) -> MeetingDetail? { loadBundled(slug) }

    /// Today-forward upcoming meetings from the bundled snapshot.
    static var upcoming: [UpcomingMeeting] {
        let all = (loadBundled("upcoming") as UpcomingFile?)?.meetings ?? []
        return futureMeetings(all)
    }

    /// Current canonical index. GitHub Pages is preferred because it is the same
    /// published contract used by Riverhead Budget Live; raw main is a second
    /// source in case a Pages deployment is briefly behind. The bundled copy is
    /// returned when neither network source can be decoded.
    static func currentIndex() async -> MeetingsIndex? {
        if let remote: MeetingsIndex = await loadRemote("index") {
            return remote
        }
        return index
    }

    /// Current canonical meeting detail with bundled offline fallback.
    static func currentMeeting(_ slug: String) async -> MeetingDetail? {
        if let remote: MeetingDetail = await loadRemote(slug) {
            return remote
        }
        return meeting(slug)
    }

    /// Current canonical upcoming schedule, filtered to today-forward meetings.
    static func currentUpcoming() async -> [UpcomingMeeting] {
        if let remote: UpcomingFile = await loadRemote("upcoming") {
            return futureMeetings(remote.meetings)
        }
        return upcoming
    }

    private static let remoteRoots = [
        "https://rike4545.github.io/Riverhead-NY-Budget-Web-App/data/meetings/",
        "https://raw.githubusercontent.com/rike4545/Riverhead-NY-Budget-Web-App/main/web/public/data/meetings/"
    ]

    private static func loadRemote<T: Decodable>(_ resource: String) async -> T? {
        for root in remoteRoots {
            guard let url = URL(string: root + resource + ".json") else { continue }

            do {
                let (data, response) = try await URLSession.shared.data(from: url)
                guard let http = response as? HTTPURLResponse,
                      (200..<300).contains(http.statusCode) else { continue }

                if let decoded = try? JSONDecoder().decode(T.self, from: data) {
                    return decoded
                }
            } catch {
                continue
            }
        }

        return nil
    }

    private static func loadBundled<T: Decodable>(_ resource: String) -> T? {
        let url = Bundle.main.url(forResource: resource, withExtension: "json", subdirectory: "MeetingsData")
            ?? Bundle.main.url(forResource: resource, withExtension: "json")
        guard let url, let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(T.self, from: data)
    }

    private static func futureMeetings(_ meetings: [UpcomingMeeting]) -> [UpcomingMeeting] {
        let today = ISO8601DateFormatter().string(from: Date()).prefix(10) // "yyyy-MM-dd"
        return meetings.filter { $0.date >= String(today) }
    }

    /// Format "2026-08-04T14:00:00Z" as "Tuesday, August 4, 2026 · 2:00 PM" using
    /// the clock time exactly as written (no timezone conversion — these are the
    /// local meeting times the Town posts).
    static func formatMeeting(_ iso: String) -> String {
        let datePart = String(iso.prefix(10))
        var day = datePart
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "yyyy-MM-dd"
        if let d = f.date(from: datePart) {
            f.dateFormat = "EEEE, MMMM d, yyyy"
            day = f.string(from: d)
        }
        guard let tRange = iso.range(of: #"T(\d{2}):(\d{2})"#, options: .regularExpression) else { return day }
        let hhmm = iso[tRange].dropFirst() // "14:00"
        let parts = hhmm.split(separator: ":")
        guard parts.count == 2, var h = Int(parts[0]) else { return day }
        let minute = String(parts[1])
        let ampm = h >= 12 ? "PM" : "AM"
        h %= 12
        if h == 0 { h = 12 }
        return "\(day) · \(h):\(minute) \(ampm)"
    }
}
